## Integer scale when possible
# Alternative version for:
# - NES & SNES: use square pixels resulting to crisper image but bigger bezels.
# - Megadrive, CD, 32x: use square pixels so 256x224 games have crisper image but bigger bezels.
# - GBA: use correct 3x2 aspect ratio. Default config renders GBA in 4x3 as it looks better due to integer scale Y.
# - GB: use black scanlines instead of original DMG colors.
# - GG: use 10x9 aspect ratio with square pixels similar to GB instead of 4x3 which actual device had.
# - Arcade: for vertical games make screen wider so it has 2x horizontal scaling resulting to square-ish screen.
default:
  # shader affects retroarch shaders
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
  # scanline affect fba2x
  scanline: false
snes:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
nes:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
n64:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
gba:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1-GBA
gb:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
gbc:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
fds:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
virtualboy:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
# Sega
sg1000:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
mastersystem:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
megadrive:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
gamegear:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
sega32x:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
segacd:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-pxl1x1
# Arcade
neogeo:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
neogeocd:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
mame:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
hbmame:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
fba:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
fbneo:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
cps1:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
cps2:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
cps3:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
naomi:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
atomiswave:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3-rotated-square
#
ngp:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
ngpc:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
gw:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
vectrex:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
lynx:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
lutro:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
wswan:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
wswanc:
  shader: integer-scaler-plus/integer-scaler-plus-dotmatrix-pxl1x1
pcengine:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
pcenginecd:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
supergrafx:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
atari800:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
atari2600:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
atari5200:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
atari7800:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
prboom:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
psx:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
colecovision:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
# Computers
c64:
  shader: integer-scaler-plus/integer-scaler-plus-no-scanlines-scr4x3
dos:
  shader: integer-scaler-plus/integer-scaler-plus-no-scanlines-scr4x3
msx:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
msx1:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
msx2:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
amiga:
  shader: integer-scaler-plus/integer-scaler-plus-no-scanlines-scr4x3
amstradcpc:
  shader: integer-scaler-plus/integer-scaler-plus-no-scanlines-scr4x3
atarist:
  shader: integer-scaler-plus/integer-scaler-plus-no-scanlines-scr4x3
zxspectrum:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
odyssey2:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
zx81:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
pcfx:
  shader: integer-scaler-plus/integer-scaler-plus-scanlines-scr4x3
x68000:
  shader: integer-scaler-plus/integer-scaler-plus-no-scanlines-scr4x3
